### ISSUE TITLE
Not working with url params (or "?" char)

### ISSUE THREAD

**Issue by gmdimitriz** [RamProg/react-native-text-link#1]
Example: 

text: "https://www.google.com/maps/dir/?api=1&sensor=true&mode=driving&destination=-18.114927,-39.159157",
onPress: () =>  console.log("click"),

it works if i put the text https://www.google.com/maps/dir/ but not with ? sign

**Comment by RamProg** [comment]
Sorry for the delay. Can you explain further, what exactly happens in this case?
